import { CountryballDef } from '../types';

export const COUNTRYBALLS: CountryballDef[] = [
  // 1-10: Classic Major Contenders
  {
    id: 'turkey',
    name: 'Turkey',
    code: 'TR',
    flagEmoji: '🇹🇷',
    primaryColor: '#E30A17',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'FEZ',
    trait: 'Bosphorus Charge - Lightning acceleration',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.05,
    weightMultiplier: 1.0,
  },
  {
    id: 'germany',
    name: 'Germany',
    code: 'DE',
    flagEmoji: '🇩🇪',
    primaryColor: '#000000',
    secondaryColor: '#DD0000',
    accentColor: '#FFCE00',
    flagStyle: 'CUSTOM',
    accessory: 'STAHLHELM',
    trait: 'Autobahn Precision - High top rolling speed',
    speedMultiplier: 1.06,
    bounceMultiplier: 0.95,
    weightMultiplier: 1.08,
  },
  {
    id: 'france',
    name: 'France',
    code: 'FR',
    flagEmoji: '🇫🇷',
    primaryColor: '#002654',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    flagStyle: 'CUSTOM',
    accessory: 'BERET',
    trait: 'Tour de France - Smooth curve drifting',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.98,
  },
  {
    id: 'brazil',
    name: 'Brazil',
    code: 'BR',
    flagEmoji: '🇧🇷',
    primaryColor: '#009739',
    secondaryColor: '#FEDD00',
    accentColor: '#012169',
    flagStyle: 'CUSTOM',
    accessory: 'HEADBAND',
    trait: 'Samba Spin - High angular elasticity',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.08,
    weightMultiplier: 0.96,
  },
  {
    id: 'usa',
    name: 'USA',
    code: 'US',
    flagEmoji: '🇺🇸',
    primaryColor: '#B22234',
    secondaryColor: '#3C3B6E',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'SUNGLASSES',
    trait: 'Freedom Nitro - Massive boost pad impulse',
    speedMultiplier: 1.07,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.1,
  },
  {
    id: 'japan',
    name: 'Japan',
    code: 'JP',
    flagEmoji: '🇯🇵',
    primaryColor: '#FFFFFF',
    secondaryColor: '#BC002D',
    accentColor: '#BC002D',
    flagStyle: 'CUSTOM',
    accessory: 'HACHIMAKI',
    trait: 'Bullet Train - Maximum streamline efficiency',
    speedMultiplier: 1.08,
    bounceMultiplier: 0.92,
    weightMultiplier: 0.94,
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    code: 'GB',
    flagEmoji: '🇬🇧',
    primaryColor: '#012169',
    secondaryColor: '#C8102E',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'TOP_HAT',
    trait: 'Gentleman Glide - Unshakable stability',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.0,
    weightMultiplier: 1.05,
  },
  {
    id: 'italy',
    name: 'Italy',
    code: 'IT',
    flagEmoji: '🇮🇹',
    primaryColor: '#009246',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE2B37',
    flagStyle: 'CUSTOM',
    accessory: 'CHEF_HAT',
    trait: 'Ferrari Pace - Explosive straightway burst',
    speedMultiplier: 1.06,
    bounceMultiplier: 1.04,
    weightMultiplier: 0.97,
  },
  {
    id: 'poland',
    name: 'Poland',
    code: 'PL',
    flagEmoji: '🇵🇱',
    primaryColor: '#DC143C',
    secondaryColor: '#FFFFFF',
    accentColor: '#DC143C',
    flagStyle: 'CUSTOM',
    accessory: 'PLUNGER',
    trait: 'Can Into Space - Extreme bumper launch',
    speedMultiplier: 1.01,
    bounceMultiplier: 1.15,
    weightMultiplier: 0.92,
  },
  {
    id: 'canada',
    name: 'Canada',
    code: 'CA',
    flagEmoji: '🇨🇦',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    flagStyle: 'CUSTOM',
    accessory: 'USHANKA',
    trait: 'Maple Armor - Immune to bumper stun',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.06,
  },

  // 11-20: Americas & Europe
  {
    id: 'mexico',
    name: 'Mexico',
    code: 'MX',
    flagEmoji: '🇲🇽',
    primaryColor: '#006847',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    flagStyle: 'CUSTOM',
    accessory: 'SOMBRERO',
    trait: 'Fiesta Bouncer - High ricochet velocity',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.12,
    weightMultiplier: 0.98,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    code: 'AR',
    flagEmoji: '🇦🇷',
    primaryColor: '#74ACDF',
    secondaryColor: '#FFFFFF',
    accentColor: '#F6B40E',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Pampa Gale - High slipstream draft',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.96,
  },
  {
    id: 'spain',
    name: 'Spain',
    code: 'ES',
    flagEmoji: '🇪🇸',
    primaryColor: '#AA151B',
    secondaryColor: '#F1BF00',
    accentColor: '#AA151B',
    flagStyle: 'CUSTOM',
    accessory: 'MATADOR',
    trait: 'Matador Dodge - Slices past hazards',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.0,
  },
  {
    id: 'sweden',
    name: 'Sweden',
    code: 'SE',
    flagEmoji: '🇸🇪',
    primaryColor: '#006AA7',
    secondaryColor: '#FECC00',
    accentColor: '#FECC00',
    flagStyle: 'CUSTOM',
    accessory: 'VIKING',
    trait: 'Nordic Steel - Low impact friction',
    speedMultiplier: 1.03,
    bounceMultiplier: 0.98,
    weightMultiplier: 1.04,
  },
  {
    id: 'india',
    name: 'India',
    code: 'IN',
    flagEmoji: '🇮🇳',
    primaryColor: '#FF9933',
    secondaryColor: '#FFFFFF',
    accentColor: '#138808',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Chakra Wheel - High rotational spin',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.0,
  },
  {
    id: 'australia',
    name: 'Australia',
    code: 'AU',
    flagEmoji: '🇦🇺',
    primaryColor: '#00008B',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    flagStyle: 'CUSTOM',
    accessory: 'CORK_HAT',
    trait: 'Outback Bound - Huge vertical airtime',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.14,
    weightMultiplier: 0.95,
  },
  {
    id: 'netherlands',
    name: 'Netherlands',
    code: 'NL',
    flagEmoji: '🇳🇱',
    primaryColor: '#AE1C28',
    secondaryColor: '#FFFFFF',
    accentColor: '#21468B',
    flagStyle: 'TRICOLOR_H',
    accessory: 'SUNGLASSES',
    trait: 'Total Football - Excellent pack navigation',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.02,
  },
  {
    id: 'south_korea',
    name: 'South Korea',
    code: 'KR',
    flagEmoji: '🇰🇷',
    primaryColor: '#FFFFFF',
    secondaryColor: '#CD2E3A',
    accentColor: '#0047A0',
    flagStyle: 'CUSTOM',
    accessory: 'HEADBAND',
    trait: 'K-Speed Cybernetic - Rapid hazard recovery',
    speedMultiplier: 1.06,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.95,
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    code: 'CH',
    flagEmoji: '🇨🇭',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'TOP_HAT',
    trait: 'Alpine Neutral - Balanced all-terrain mastery',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.02,
  },
  {
    id: 'greece',
    name: 'Greece',
    code: 'GR',
    flagEmoji: '🇬🇷',
    primaryColor: '#0D5EAF',
    secondaryColor: '#FFFFFF',
    accentColor: '#0D5EAF',
    flagStyle: 'CUSTOM',
    accessory: 'MATADOR',
    trait: 'Spartan Spirit - Unyielding wall rebounds',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.08,
    weightMultiplier: 1.04,
  },

  // 21-35: Global Powers & Regional Giants
  {
    id: 'china',
    name: 'China',
    code: 'CN',
    flagEmoji: '🇨🇳',
    primaryColor: '#DE2910',
    secondaryColor: '#FFDE00',
    accentColor: '#FFDE00',
    flagStyle: 'CUSTOM',
    accessory: 'HACHIMAKI',
    trait: 'Dragon Surge - Steady heavy momentum',
    speedMultiplier: 1.05,
    bounceMultiplier: 0.96,
    weightMultiplier: 1.12,
  },
  {
    id: 'egypt',
    name: 'Egypt',
    code: 'EG',
    flagEmoji: '🇪🇬',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#000000',
    flagStyle: 'TRICOLOR_H',
    accessory: 'FEZ',
    trait: 'Pharaoh Curse - Slows down nearby rivals',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.03,
  },
  {
    id: 'saudi_arabia',
    name: 'Saudi Arabia',
    code: 'SA',
    flagEmoji: '🇸🇦',
    primaryColor: '#006C35',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Desert Falcon - High thermal glide',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.0,
    weightMultiplier: 1.05,
  },
  {
    id: 'portugal',
    name: 'Portugal',
    code: 'PT',
    flagEmoji: '🇵🇹',
    primaryColor: '#006600',
    secondaryColor: '#FF0000',
    accentColor: '#FFCC00',
    flagStyle: 'CUSTOM',
    accessory: 'HEADBAND',
    trait: 'Navigators Way - Flawless funnel pathing',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.98,
  },
  {
    id: 'morocco',
    name: 'Morocco',
    code: 'MA',
    flagEmoji: '🇲🇦',
    primaryColor: '#C1272D',
    secondaryColor: '#006233',
    accentColor: '#006233',
    flagStyle: 'CUSTOM',
    accessory: 'FEZ',
    trait: 'Atlas Lion - Fearless downhill sprints',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.06,
    weightMultiplier: 0.99,
  },
  {
    id: 'pakistan',
    name: 'Pakistan',
    code: 'PK',
    flagEmoji: '🇵🇰',
    primaryColor: '#01411C',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'K2 Climber - Dominates steep inclines',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.05,
    weightMultiplier: 1.01,
  },
  {
    id: 'norway',
    name: 'Norway',
    code: 'NO',
    flagEmoji: '🇳🇴',
    primaryColor: '#BA0C2F',
    secondaryColor: '#FFFFFF',
    accentColor: '#00205B',
    flagStyle: 'CROSS_NORDIC',
    accessory: 'VIKING',
    trait: 'Fjord Runner - Ice and water resistance',
    speedMultiplier: 1.05,
    bounceMultiplier: 0.98,
    weightMultiplier: 1.06,
  },
  {
    id: 'denmark',
    name: 'Denmark',
    code: 'DK',
    flagEmoji: '🇩🇰',
    primaryColor: '#C8102E',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    flagStyle: 'CROSS_NORDIC',
    accessory: 'VIKING',
    trait: 'Lego Brick - Shock absorption armor',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.08,
  },
  {
    id: 'finland',
    name: 'Finland',
    code: 'FI',
    flagEmoji: '🇫🇮',
    primaryColor: '#FFFFFF',
    secondaryColor: '#002F6C',
    accentColor: '#002F6C',
    flagStyle: 'CROSS_NORDIC',
    accessory: 'USHANKA',
    trait: 'Sisu Grit - Unstoppable forward drive',
    speedMultiplier: 1.04,
    bounceMultiplier: 0.97,
    weightMultiplier: 1.05,
  },
  {
    id: 'iceland',
    name: 'Iceland',
    code: 'IS',
    flagEmoji: '🇮🇸',
    primaryColor: '#02529C',
    secondaryColor: '#FFFFFF',
    accentColor: '#DC1E35',
    flagStyle: 'CROSS_NORDIC',
    accessory: 'VIKING',
    trait: 'Geyser Launch - Massive vertical bounce',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.13,
    weightMultiplier: 0.97,
  },
  {
    id: 'austria',
    name: 'Austria',
    code: 'AT',
    flagEmoji: '🇦🇹',
    primaryColor: '#ED2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    flagStyle: 'TRICOLOR_H',
    accessory: 'TOP_HAT',
    trait: 'Waltz Rhythm - Fluid curve transitions',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.01,
  },
  {
    id: 'belgium',
    name: 'Belgium',
    code: 'BE',
    flagEmoji: '🇧🇪',
    primaryColor: '#000000',
    secondaryColor: '#FDDA24',
    accentColor: '#EF3340',
    flagStyle: 'TRICOLOR_V',
    accessory: 'BERET',
    trait: 'Chocolate Smooth - Frictionless rolling',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.0,
    weightMultiplier: 1.03,
  },
  {
    id: 'ireland',
    name: 'Ireland',
    code: 'IE',
    flagEmoji: '🇮🇪',
    primaryColor: '#169B62',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF883E',
    flagStyle: 'TRICOLOR_V',
    accessory: 'TOP_HAT',
    trait: 'Lucky Clover - Avoids hazardous traps',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.07,
    weightMultiplier: 0.96,
  },
  {
    id: 'colombia',
    name: 'Colombia',
    code: 'CO',
    flagEmoji: '🇨🇴',
    primaryColor: '#FCD116',
    secondaryColor: '#003893',
    accentColor: '#CE1126',
    flagStyle: 'TRICOLOR_H',
    accessory: 'SOMBRERO',
    trait: 'Coffee Rush - High initial speed off start',
    speedMultiplier: 1.06,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.97,
  },
  {
    id: 'chile',
    name: 'Chile',
    code: 'CL',
    flagEmoji: '🇨🇱',
    primaryColor: '#0039A6',
    secondaryColor: '#FFFFFF',
    accentColor: '#D52B1E',
    flagStyle: 'CUSTOM',
    accessory: 'SOMBRERO',
    trait: 'Andes Narrow - Squeezes through dense packs',
    speedMultiplier: 1.05,
    bounceMultiplier: 0.99,
    weightMultiplier: 0.96,
  },

  // 36-50: Africa, Asia & Eastern Europe
  {
    id: 'nigeria',
    name: 'Nigeria',
    code: 'NG',
    flagEmoji: '🇳🇬',
    primaryColor: '#008751',
    secondaryColor: '#FFFFFF',
    accentColor: '#008751',
    flagStyle: 'TRICOLOR_V',
    accessory: 'HEADBAND',
    trait: 'Super Eagle - High top speed soaring',
    speedMultiplier: 1.06,
    bounceMultiplier: 1.04,
    weightMultiplier: 0.98,
  },
  {
    id: 'south_africa',
    name: 'South Africa',
    code: 'ZA',
    flagEmoji: '🇿🇦',
    primaryColor: '#007A4D',
    secondaryColor: '#FFB612',
    accentColor: '#DE3831',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Rainbow Power - Balanced boost handling',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.04,
  },
  {
    id: 'ukraine',
    name: 'Ukraine',
    code: 'UA',
    flagEmoji: '🇺🇦',
    primaryColor: '#005BBB',
    secondaryColor: '#FFD500',
    accentColor: '#FFD500',
    flagStyle: 'BICOLOR_H',
    accessory: 'USHANKA',
    trait: 'Steppe Wind - Persistent speed retention',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.02,
  },
  {
    id: 'czechia',
    name: 'Czechia',
    code: 'CZ',
    flagEmoji: '🇨🇿',
    primaryColor: '#11457E',
    secondaryColor: '#FFFFFF',
    accentColor: '#D7141A',
    flagStyle: 'CUSTOM',
    accessory: 'BERET',
    trait: 'Bohemian Crystal - High bounce elasticity',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.09,
    weightMultiplier: 0.99,
  },
  {
    id: 'hungary',
    name: 'Hungary',
    code: 'HU',
    flagEmoji: '🇭🇺',
    primaryColor: '#CE2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#477050',
    flagStyle: 'TRICOLOR_H',
    accessory: 'BERET',
    trait: 'Magyar Rider - Excellent lane cuts',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.0,
  },
  {
    id: 'romania',
    name: 'Romania',
    code: 'RO',
    flagEmoji: '🇷🇴',
    primaryColor: '#002B7F',
    secondaryColor: '#FCD116',
    accentColor: '#CE1126',
    flagStyle: 'TRICOLOR_V',
    accessory: 'BERET',
    trait: 'Carpathian Wolf - Aggressive overtaking',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.01,
  },
  {
    id: 'thailand',
    name: 'Thailand',
    code: 'TH',
    flagEmoji: '🇹🇭',
    primaryColor: '#A51931',
    secondaryColor: '#F4F5F8',
    accentColor: '#2D2A4A',
    flagStyle: 'CUSTOM',
    accessory: 'HEADBAND',
    trait: 'Muay Thai Kick - Powerful ball collisions',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.08,
    weightMultiplier: 0.98,
  },
  {
    id: 'vietnam',
    name: 'Vietnam',
    code: 'VN',
    flagEmoji: '🇻🇳',
    primaryColor: '#DA251D',
    secondaryColor: '#FFFF00',
    accentColor: '#FFFF00',
    flagStyle: 'SOLID_STAR',
    accessory: 'SUN_CAP',
    trait: 'Lotus Bloom - Agile obstacle navigation',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.05,
    weightMultiplier: 0.95,
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    code: 'ID',
    flagEmoji: '🇮🇩',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    flagStyle: 'BICOLOR_H',
    accessory: 'FEZ',
    trait: 'Island Hopper - Rapid switchback turning',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.06,
    weightMultiplier: 0.96,
  },
  {
    id: 'malaysia',
    name: 'Malaysia',
    code: 'MY',
    flagEmoji: '🇲🇾',
    primaryColor: '#CC0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#000066',
    flagStyle: 'CANTON_STRIPES',
    accessory: 'FEZ',
    trait: 'Malayan Tiger - Quick dash bursts',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.99,
  },
  {
    id: 'philippines',
    name: 'Philippines',
    code: 'PH',
    flagEmoji: '🇵🇭',
    primaryColor: '#0038A8',
    secondaryColor: '#CE1126',
    accentColor: '#FCD116',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Sun & Stars - Resilient hazard bounce',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.07,
    weightMultiplier: 0.97,
  },
  {
    id: 'singapore',
    name: 'Singapore',
    code: 'SG',
    flagEmoji: '🇸🇬',
    primaryColor: '#ED2939',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    flagStyle: 'BICOLOR_H',
    accessory: 'SUNGLASSES',
    trait: 'Lion City - Precision mechanical drift',
    speedMultiplier: 1.07,
    bounceMultiplier: 0.95,
    weightMultiplier: 1.02,
  },
  {
    id: 'new_zealand',
    name: 'New Zealand',
    code: 'NZ',
    flagEmoji: '🇳🇿',
    primaryColor: '#00247D',
    secondaryColor: '#CC142B',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'SUNGLASSES',
    trait: 'Kiwi Glide - Smooth low-gravity rolls',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.05,
    weightMultiplier: 0.98,
  },
  {
    id: 'croatia',
    name: 'Croatia',
    code: 'HR',
    flagEmoji: '🇭🇷',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#171796',
    flagStyle: 'TRICOLOR_H',
    accessory: 'HEADBAND',
    trait: 'Checkerboard Tactics - Strategic blocking',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.02,
  },
  {
    id: 'serbia',
    name: 'Serbia',
    code: 'RS',
    flagEmoji: '🇷🇸',
    primaryColor: '#C6363C',
    secondaryColor: '#0C4076',
    accentColor: '#FFFFFF',
    flagStyle: 'TRICOLOR_H',
    accessory: 'STAHLHELM',
    trait: 'Eagle Crest - Heavy bump knockbacks',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.07,
  },

  // 51-65: Middle East, Africa & Americas
  {
    id: 'peru',
    name: 'Peru',
    code: 'PE',
    flagEmoji: '🇵🇪',
    primaryColor: '#D91023',
    secondaryColor: '#FFFFFF',
    accentColor: '#D91023',
    flagStyle: 'TRICOLOR_V',
    accessory: 'USHANKA',
    trait: 'Inca Trail - Mountain slope dominance',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.0,
  },
  {
    id: 'algeria',
    name: 'Algeria',
    code: 'DZ',
    flagEmoji: '🇩🇿',
    primaryColor: '#006233',
    secondaryColor: '#FFFFFF',
    accentColor: '#D21034',
    flagStyle: 'BICOLOR_V',
    accessory: 'FEZ',
    trait: 'Desert Fox - High sand traction',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.0,
  },
  {
    id: 'kenya',
    name: 'Kenya',
    code: 'KE',
    flagEmoji: '🇰🇪',
    primaryColor: '#000000',
    secondaryColor: '#BB0000',
    accentColor: '#006600',
    flagStyle: 'TRICOLOR_H',
    accessory: 'HEADBAND',
    trait: 'Marathon Legend - Infinite endurance speed',
    speedMultiplier: 1.07,
    bounceMultiplier: 0.98,
    weightMultiplier: 0.94,
  },
  {
    id: 'ethiopia',
    name: 'Ethiopia',
    code: 'ET',
    flagEmoji: '🇪🇹',
    primaryColor: '#009A44',
    secondaryColor: '#FED100',
    accentColor: '#EF3340',
    flagStyle: 'TRICOLOR_H',
    accessory: 'HEADBAND',
    trait: 'Highland Pacer - High continuous velocity',
    speedMultiplier: 1.06,
    bounceMultiplier: 1.0,
    weightMultiplier: 0.95,
  },
  {
    id: 'ghana',
    name: 'Ghana',
    code: 'GH',
    flagEmoji: '🇬🇭',
    primaryColor: '#CE1126',
    secondaryColor: '#FCD116',
    accentColor: '#006B3F',
    flagStyle: 'TRICOLOR_H',
    accessory: 'HEADBAND',
    trait: 'Black Star - Stellar booster acceleration',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.04,
    weightMultiplier: 0.98,
  },
  {
    id: 'senegal',
    name: 'Senegal',
    code: 'SN',
    flagEmoji: '🇸🇳',
    primaryColor: '#00853F',
    secondaryColor: '#FDEF42',
    accentColor: '#E31B23',
    flagStyle: 'TRICOLOR_V',
    accessory: 'HEADBAND',
    trait: 'Teranga Rhythm - Agile wave motion',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.05,
    weightMultiplier: 0.97,
  },
  {
    id: 'cameron',
    name: 'Cameroon',
    code: 'CM',
    flagEmoji: '🇨🇲',
    primaryColor: '#007A5E',
    secondaryColor: '#CE1126',
    accentColor: '#FCD116',
    flagStyle: 'TRICOLOR_V',
    accessory: 'HEADBAND',
    trait: 'Indomitable Lion - Unshakable impact force',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.06,
  },
  {
    id: 'ivory_coast',
    name: 'Ivory Coast',
    code: 'CI',
    flagEmoji: '🇨🇮',
    primaryColor: '#F77F00',
    secondaryColor: '#FFFFFF',
    accentColor: '#009E60',
    flagStyle: 'TRICOLOR_V',
    accessory: 'HEADBAND',
    trait: 'Elephant Charge - Massive forward mass',
    speedMultiplier: 1.03,
    bounceMultiplier: 0.99,
    weightMultiplier: 1.09,
  },
  {
    id: 'uae',
    name: 'UAE',
    code: 'AE',
    flagEmoji: '🇦🇪',
    primaryColor: '#00732F',
    secondaryColor: '#FFFFFF',
    accentColor: '#000000',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Hyperloop Boost - Instant pad acceleration',
    speedMultiplier: 1.07,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.02,
  },
  {
    id: 'qatar',
    name: 'Qatar',
    code: 'QA',
    flagEmoji: '🇶🇦',
    primaryColor: '#8D1B3D',
    secondaryColor: '#FFFFFF',
    accentColor: '#8D1B3D',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Dune Drifter - Smooth high-speed sweeps',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.03,
  },
  {
    id: 'uruguay',
    name: 'Uruguay',
    code: 'UY',
    flagEmoji: '🇺🇾',
    primaryColor: '#0038A8',
    secondaryColor: '#FFFFFF',
    accentColor: '#FCD116',
    flagStyle: 'CANTON_STRIPES',
    accessory: 'SUN_CAP',
    trait: 'Garra Charrua - Clutch final sprint',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.98,
  },
  {
    id: 'ecuador',
    name: 'Ecuador',
    code: 'EC',
    flagEmoji: '🇪🇨',
    primaryColor: '#FFDD00',
    secondaryColor: '#034EA2',
    accentColor: '#ED1C24',
    flagStyle: 'TRICOLOR_H',
    accessory: 'SOMBRERO',
    trait: 'Equator Slingshot - Boosts around center track',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.98,
  },
  {
    id: 'venezuela',
    name: 'Venezuela',
    code: 'VE',
    flagEmoji: '🇻🇪',
    primaryColor: '#FCD116',
    secondaryColor: '#003893',
    accentColor: '#CE1126',
    flagStyle: 'TRICOLOR_H',
    accessory: 'SUN_CAP',
    trait: 'Angel Falls - High diving velocity',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.97,
  },
  {
    id: 'finland_lapland',
    name: 'Slovakia',
    code: 'SK',
    flagEmoji: '🇸🇰',
    primaryColor: '#EE1C25',
    secondaryColor: '#FFFFFF',
    accentColor: '#0B3A82',
    flagStyle: 'TRICOLOR_H',
    accessory: 'USHANKA',
    trait: 'Tatra Shield - Deflects incoming balls',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.04,
  },
  {
    id: 'slovenia',
    name: 'Slovenia',
    code: 'SI',
    flagEmoji: '🇸🇮',
    primaryColor: '#FFFFFF',
    secondaryColor: '#005CE6',
    accentColor: '#ED1C24',
    flagStyle: 'TRICOLOR_H',
    accessory: 'BERET',
    trait: 'Triglav Ascent - High slope velocity',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.01,
  },

  // 66-80: Europe, Asia & Caribbean
  {
    id: 'bulgaria',
    name: 'Bulgaria',
    code: 'BG',
    flagEmoji: '🇧🇬',
    primaryColor: '#FFFFFF',
    secondaryColor: '#00966E',
    accentColor: '#D62612',
    flagStyle: 'TRICOLOR_H',
    accessory: 'BERET',
    trait: 'Balkan Stride - Heavy steady rolling',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.05,
  },
  {
    id: 'jamaica',
    name: 'Jamaica',
    code: 'JM',
    flagEmoji: '🇯🇲',
    primaryColor: '#000000',
    secondaryColor: '#FED100',
    accentColor: '#009B3A',
    flagStyle: 'SALTIRE',
    accessory: 'HEADBAND',
    trait: 'Lightning Bolt - Unmatched top sprint speed',
    speedMultiplier: 1.09,
    bounceMultiplier: 0.98,
    weightMultiplier: 0.93,
  },
  {
    id: 'cuba',
    name: 'Cuba',
    code: 'CU',
    flagEmoji: '🇨🇺',
    primaryColor: '#002A8F',
    secondaryColor: '#FFFFFF',
    accentColor: '#CF142B',
    flagStyle: 'CUSTOM',
    accessory: 'BERET',
    trait: 'Caribbean Rhythm - Smooth bounce cadence',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.06,
    weightMultiplier: 0.99,
  },
  {
    id: 'costa_rica',
    name: 'Costa Rica',
    code: 'CR',
    flagEmoji: '🇨🇷',
    primaryColor: '#002B7F',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Pura Vida - Calm hazard recovery',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.04,
    weightMultiplier: 0.98,
  },
  {
    id: 'panama',
    name: 'Panama',
    code: 'PA',
    flagEmoji: '🇵🇦',
    primaryColor: '#FFFFFF',
    secondaryColor: '#005293',
    accentColor: '#D21034',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Canal Flow - Effortless bottleneck passing',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.98,
  },
  {
    id: 'kazakhstan',
    name: 'Kazakhstan',
    code: 'KZ',
    flagEmoji: '🇰🇿',
    primaryColor: '#00AFCA',
    secondaryColor: '#FEC50C',
    accentColor: '#FEC50C',
    flagStyle: 'CUSTOM',
    accessory: 'USHANKA',
    trait: 'Brick Countryball - Unshakable box stability',
    speedMultiplier: 1.04,
    bounceMultiplier: 0.94,
    weightMultiplier: 1.15,
  },
  {
    id: 'uzbekistan',
    name: 'Uzbekistan',
    code: 'UZ',
    flagEmoji: '🇺🇿',
    primaryColor: '#1EB53A',
    secondaryColor: '#0099B5',
    accentColor: '#CE1126',
    flagStyle: 'TRICOLOR_H',
    accessory: 'TURBAN',
    trait: 'Silk Road - Strategic cornering cuts',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.02,
  },
  {
    id: 'mongolia',
    name: 'Mongolia',
    code: 'MN',
    flagEmoji: '🇲🇳',
    primaryColor: '#E4002B',
    secondaryColor: '#0066B3',
    accentColor: '#FFD100',
    flagStyle: 'TRICOLOR_V',
    accessory: 'USHANKA',
    trait: 'Steppe Nomad - Ruthless downhill charges',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.06,
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    code: 'BD',
    flagEmoji: '🇧🇩',
    primaryColor: '#006A4E',
    secondaryColor: '#F42A41',
    accentColor: '#F42A41',
    flagStyle: 'SUN_DISC',
    accessory: 'TURBAN',
    trait: 'Bengal Tiger - High energy pounce',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.06,
    weightMultiplier: 0.97,
  },
  {
    id: 'sri_lanka',
    name: 'Sri Lanka',
    code: 'LK',
    flagEmoji: '🇱🇰',
    primaryColor: '#8D153A',
    secondaryColor: '#FFBE29',
    accentColor: '#00534E',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Lion Blade - Cuts through bumper fields',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.05,
    weightMultiplier: 1.01,
  },
  {
    id: 'nepal',
    name: 'Nepal',
    code: 'NP',
    flagEmoji: '🇳🇵',
    primaryColor: '#DC143C',
    secondaryColor: '#003893',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'HEADBAND',
    trait: 'Everest Apex - Extreme vertical jump resilience',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.15,
    weightMultiplier: 0.93,
  },
  {
    id: 'georgia',
    name: 'Georgia',
    code: 'GE',
    flagEmoji: '🇬🇪',
    primaryColor: '#FFFFFF',
    secondaryColor: '#FF0000',
    accentColor: '#FF0000',
    flagStyle: 'CUSTOM',
    accessory: 'USHANKA',
    trait: 'Caucasus Guard - High collision defense',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.05,
  },
  {
    id: 'azerbaijan',
    name: 'Azerbaijan',
    code: 'AZ',
    flagEmoji: '🇦🇿',
    primaryColor: '#00B5E2',
    secondaryColor: '#EF3340',
    accentColor: '#509E2F',
    flagStyle: 'TRICOLOR_H',
    accessory: 'FEZ',
    trait: 'Land of Fire - Immune to flamethrower stun',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.0,
  },
  {
    id: 'armenia',
    name: 'Armenia',
    code: 'AM',
    flagEmoji: '🇦🇲',
    primaryColor: '#D90012',
    secondaryColor: '#0033A0',
    accentColor: '#F2A800',
    flagStyle: 'TRICOLOR_H',
    accessory: 'USHANKA',
    trait: 'Ararat Fortress - Rock solid ground contact',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.08,
  },
  {
    id: 'cyprus',
    name: 'Cyprus',
    code: 'CY',
    flagEmoji: '🇨🇾',
    primaryColor: '#FFFFFF',
    secondaryColor: '#D47600',
    accentColor: '#4E5B31',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Copper Isle - Superconductive booster roll',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.98,
  },

  // 81-100: Nordic, Baltic, Balkan, Islands & Diverse Global Nations
  {
    id: 'estonia',
    name: 'Estonia',
    code: 'EE',
    flagEmoji: '🇪🇪',
    primaryColor: '#0072CE',
    secondaryColor: '#000000',
    accentColor: '#FFFFFF',
    flagStyle: 'TRICOLOR_H',
    accessory: 'USHANKA',
    trait: 'E-Residency - High-tech optimal pathing',
    speedMultiplier: 1.05,
    bounceMultiplier: 0.98,
    weightMultiplier: 1.0,
  },
  {
    id: 'latvia',
    name: 'Latvia',
    code: 'LV',
    flagEmoji: '🇱🇻',
    primaryColor: '#9E3039',
    secondaryColor: '#FFFFFF',
    accentColor: '#9E3039',
    flagStyle: 'TRICOLOR_H',
    accessory: 'USHANKA',
    trait: 'Baltic Pine - Natural bumper springiness',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.05,
    weightMultiplier: 1.01,
  },
  {
    id: 'lithuania',
    name: 'Lithuania',
    code: 'LT',
    flagEmoji: '🇱🇹',
    primaryColor: '#FDB913',
    secondaryColor: '#006A44',
    accentColor: '#C1272D',
    flagStyle: 'TRICOLOR_H',
    accessory: 'HEADBAND',
    trait: 'Basketball Jump - High rebound precision',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.09,
    weightMultiplier: 0.97,
  },
  {
    id: 'luxembourg',
    name: 'Luxembourg',
    code: 'LU',
    flagEmoji: '🇱🇺',
    primaryColor: '#EA141D',
    secondaryColor: '#FFFFFF',
    accentColor: '#00A1DE',
    flagStyle: 'TRICOLOR_H',
    accessory: 'TOP_HAT',
    trait: 'Grand Ducal - Platinum smooth gliding',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.0,
    weightMultiplier: 1.04,
  },
  {
    id: 'monaco',
    name: 'Monaco',
    code: 'MC',
    flagEmoji: '🇲🇨',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    flagStyle: 'BICOLOR_H',
    accessory: 'SUNGLASSES',
    trait: 'Grand Prix - S-tier hair-pin cornering',
    speedMultiplier: 1.08,
    bounceMultiplier: 0.95,
    weightMultiplier: 0.95,
  },
  {
    id: 'malta',
    name: 'Malta',
    code: 'MT',
    flagEmoji: '🇲🇹',
    primaryColor: '#FFFFFF',
    secondaryColor: '#CF142B',
    accentColor: '#CF142B',
    flagStyle: 'BICOLOR_V',
    accessory: 'TOP_HAT',
    trait: 'Knight Cross - Unstoppable forward charge',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.05,
  },
  {
    id: 'albania',
    name: 'Albania',
    code: 'AL',
    flagEmoji: '🇦🇱',
    primaryColor: '#E41E20',
    secondaryColor: '#000000',
    accentColor: '#000000',
    flagStyle: 'CUSTOM',
    accessory: 'FEZ',
    trait: 'Double-Headed Eagle - Aerial glide recovery',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.06,
    weightMultiplier: 0.98,
  },
  {
    id: 'bosnia',
    name: 'Bosnia & Herzegovina',
    code: 'BA',
    flagEmoji: '🇧🇦',
    primaryColor: '#002395',
    secondaryColor: '#FECB00',
    accentColor: '#FFFFFF',
    flagStyle: 'CUSTOM',
    accessory: 'FEZ',
    trait: 'Golden Lily - Resilient obstacle bounces',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.01,
  },
  {
    id: 'north_macedonia',
    name: 'North Macedonia',
    code: 'MK',
    flagEmoji: '🇲🇰',
    primaryColor: '#D20000',
    secondaryColor: '#FFE600',
    accentColor: '#FFE600',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Vergina Sun - Blinding straightaway speed',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.99,
  },
  {
    id: 'tunisia',
    name: 'Tunisia',
    code: 'TN',
    flagEmoji: '🇹🇳',
    primaryColor: '#E70013',
    secondaryColor: '#FFFFFF',
    accentColor: '#E70013',
    flagStyle: 'CUSTOM',
    accessory: 'FEZ',
    trait: 'Carthage Vanguard - Fearless collision bursts',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.0,
  },
  {
    id: 'jordan',
    name: 'Jordan',
    code: 'JO',
    flagEmoji: '🇯🇴',
    primaryColor: '#000000',
    secondaryColor: '#FFFFFF',
    accentColor: '#007A3D',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Petra Guardian - Solid impact deflection',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.04,
  },
  {
    id: 'lebanon',
    name: 'Lebanon',
    code: 'LB',
    flagEmoji: '🇱🇧',
    primaryColor: '#ED1C24',
    secondaryColor: '#FFFFFF',
    accentColor: '#00A651',
    flagStyle: 'TRICOLOR_H',
    accessory: 'FEZ',
    trait: 'Cedar Root - Grounded center of gravity',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.07,
  },
  {
    id: 'kuwait',
    name: 'Kuwait',
    code: 'KW',
    flagEmoji: '🇰🇼',
    primaryColor: '#007A3D',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Gulf Current - High velocity straightaways',
    speedMultiplier: 1.06,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.02,
  },
  {
    id: 'bahrain',
    name: 'Bahrain',
    code: 'BH',
    flagEmoji: '🇧🇭',
    primaryColor: '#CE1126',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Pearl Diver - Rapid tunnel traversal',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.97,
  },
  {
    id: 'oman',
    name: 'Oman',
    code: 'OM',
    flagEmoji: '🇴🇲',
    primaryColor: '#DB161B',
    secondaryColor: '#FFFFFF',
    accentColor: '#008000',
    flagStyle: 'CUSTOM',
    accessory: 'TURBAN',
    trait: 'Frankincense Drift - Unmatched friction reduction',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.01,
  },
  {
    id: 'fiji',
    name: 'Fiji',
    code: 'FJ',
    flagEmoji: '🇫🇯',
    primaryColor: '#68BFE5',
    secondaryColor: '#FFFFFF',
    accentColor: '#C8102E',
    flagStyle: 'CUSTOM',
    accessory: 'HEADBAND',
    trait: 'Rugby Tackle - Power knocks through crowds',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.08,
    weightMultiplier: 1.08,
  },
  {
    id: 'papua_new_guinea',
    name: 'Papua New Guinea',
    code: 'PG',
    flagEmoji: '🇵🇬',
    primaryColor: '#CE1126',
    secondaryColor: '#000000',
    accentColor: '#FCD116',
    flagStyle: 'DIAGONAL_SPLIT',
    accessory: 'HEADBAND',
    trait: 'Bird of Paradise - High soaring jump arc',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.11,
    weightMultiplier: 0.95,
  },
  {
    id: 'zimbabwe',
    name: 'Zimbabwe',
    code: 'ZW',
    flagEmoji: '🇿🇼',
    primaryColor: '#006400',
    secondaryColor: '#FFD700',
    accentColor: '#D40000',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Victoria Falls - Cascading velocity build',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.03,
    weightMultiplier: 1.01,
  },
  {
    id: 'tanzania',
    name: 'Tanzania',
    code: 'TZ',
    flagEmoji: '🇹🇿',
    primaryColor: '#1EB53A',
    secondaryColor: '#00A3DD',
    accentColor: '#FCD116',
    flagStyle: 'DIAGONAL_SPLIT',
    accessory: 'HEADBAND',
    trait: 'Kilimanjaro Peak - Huge vertical drop power',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.03,
  },
  {
    id: 'madagascar',
    name: 'Madagascar',
    code: 'MG',
    flagEmoji: '🇲🇬',
    primaryColor: '#FFFFFF',
    secondaryColor: '#FC3D32',
    accentColor: '#007E3A',
    flagStyle: 'CUSTOM',
    accessory: 'SUN_CAP',
    trait: 'Baobab Core - Unshakable center of gravity',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.06,
    weightMultiplier: 1.02,
  },
];
