import { CountryballDef } from '../types';

export const COUNTRYBALLS: CountryballDef[] = [
  {
    id: 'turkey',
    name: 'Turkey',
    code: 'TR',
    flagEmoji: '🇹🇷',
    primaryColor: '#E30A17',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    accessory: 'FEZ',
    trait: 'Bosphorus Charge - Quick bursts of agility',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.05,
    weightMultiplier: 1.0,
  },
  {
    id: 'germany',
    name: 'Germany',
    code: 'DE',
    flagEmoji: '🇩🇪',
    primaryColor: '#000000',
    secondaryColor: '#DD0000',
    accentColor: '#FFCE00',
    accessory: 'STAHLHELM',
    trait: 'Autobahn Precision - High top rolling speed',
    speedMultiplier: 1.06,
    bounceMultiplier: 0.95,
    weightMultiplier: 1.08,
  },
  {
    id: 'france',
    name: 'France',
    code: 'FR',
    flagEmoji: '🇫🇷',
    primaryColor: '#002654',
    secondaryColor: '#FFFFFF',
    accentColor: '#ED2939',
    accessory: 'BERET',
    trait: 'Tour de France - Excellent curve momentum',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.98,
  },
  {
    id: 'brazil',
    name: 'Brazil',
    code: 'BR',
    flagEmoji: '🇧🇷',
    primaryColor: '#009739',
    secondaryColor: '#FEDD00',
    accentColor: '#012169',
    accessory: 'HEADBAND',
    trait: 'Samba Spin - High angular elasticity',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.08,
    weightMultiplier: 0.96,
  },
  {
    id: 'usa',
    name: 'USA',
    code: 'US',
    flagEmoji: '🇺🇸',
    primaryColor: '#B22234',
    secondaryColor: '#FFFFFF',
    accentColor: '#3C3B6E',
    accessory: 'SUNGLASSES',
    trait: 'Freedom Nitro - Heavy impact ramming',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.02,
    weightMultiplier: 1.1,
  },
  {
    id: 'japan',
    name: 'Japan',
    code: 'JP',
    flagEmoji: '🇯🇵',
    primaryColor: '#FFFFFF',
    secondaryColor: '#BC002D',
    accentColor: '#BC002D',
    accessory: 'HACHIMAKI',
    trait: 'Bullet Train - Maximum straightaway velocity',
    speedMultiplier: 1.07,
    bounceMultiplier: 0.94,
    weightMultiplier: 0.94,
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    code: 'UK',
    flagEmoji: '🇬🇧',
    primaryColor: '#012169',
    secondaryColor: '#C8102E',
    accentColor: '#FFFFFF',
    accessory: 'TOP_HAT',
    trait: 'Royal Guard - Super stable center of mass',
    speedMultiplier: 1.01,
    bounceMultiplier: 0.98,
    weightMultiplier: 1.05,
  },
  {
    id: 'italy',
    name: 'Italy',
    code: 'IT',
    flagEmoji: '🇮🇹',
    primaryColor: '#009246',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE2B37',
    accessory: 'CHEF_HAT',
    trait: 'Monza Slipstream - Quick rebound on walls',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.06,
    weightMultiplier: 0.97,
  },
  {
    id: 'poland',
    name: 'Poland',
    code: 'PL',
    flagEmoji: '🇵🇱',
    primaryColor: '#DC143C',
    secondaryColor: '#FFFFFF',
    accentColor: '#FFFFFF',
    accessory: 'PLUNGER',
    trait: 'Can Into Space - Extreme bumper spring launch',
    speedMultiplier: 1.02,
    bounceMultiplier: 1.12,
    weightMultiplier: 0.93,
  },
  {
    id: 'canada',
    name: 'Canada',
    code: 'CA',
    flagEmoji: '🇨🇦',
    primaryColor: '#FF0000',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    accessory: 'USHANKA',
    trait: 'Ice Glider - Unaffected by friction zones',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.01,
    weightMultiplier: 1.02,
  },
  {
    id: 'mexico',
    name: 'Mexico',
    code: 'MX',
    flagEmoji: '🇲🇽',
    primaryColor: '#006847',
    secondaryColor: '#FFFFFF',
    accentColor: '#CE1126',
    accessory: 'SOMBRERO',
    trait: 'Fiesta Rush - Explosive launch momentum',
    speedMultiplier: 1.04,
    bounceMultiplier: 1.07,
    weightMultiplier: 0.98,
  },
  {
    id: 'argentina',
    name: 'Argentina',
    code: 'AR',
    flagEmoji: '🇦🇷',
    primaryColor: '#74ACDF',
    secondaryColor: '#FFFFFF',
    accentColor: '#F6B40E',
    accessory: 'SUN_CAP',
    trait: 'Pampas Glide - Smooth drift along rails',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.02,
    weightMultiplier: 0.99,
  },
  {
    id: 'spain',
    name: 'Spain',
    code: 'ES',
    flagEmoji: '🇪🇸',
    primaryColor: '#AA151B',
    secondaryColor: '#F1BF00',
    accentColor: '#AA151B',
    accessory: 'MATADOR',
    trait: 'Matador Dodge - Deflects off obstacles gracefully',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.04,
    weightMultiplier: 1.0,
  },
  {
    id: 'sweden',
    name: 'Sweden',
    code: 'SE',
    flagEmoji: '🇸🇪',
    primaryColor: '#006AA7',
    secondaryColor: '#FECC00',
    accentColor: '#FECC00',
    accessory: 'VIKING',
    trait: 'Viking Raid - Unstoppable heavy momentum',
    speedMultiplier: 1.02,
    bounceMultiplier: 0.96,
    weightMultiplier: 1.09,
  },
  {
    id: 'india',
    name: 'India',
    code: 'IN',
    flagEmoji: '🇮🇳',
    primaryColor: '#FF9933',
    secondaryColor: '#FFFFFF',
    accentColor: '#138808',
    accessory: 'TURBAN',
    trait: 'Chakra Spin - Rapid recovery from vortexes',
    speedMultiplier: 1.05,
    bounceMultiplier: 1.03,
    weightMultiplier: 0.97,
  },
  {
    id: 'australia',
    name: 'Australia',
    code: 'AU',
    flagEmoji: '🇦🇺',
    primaryColor: '#00008B',
    secondaryColor: '#FFFFFF',
    accentColor: '#FF0000',
    accessory: 'CORK_HAT',
    trait: 'Outback Kangaroo - High rebound jump height',
    speedMultiplier: 1.03,
    bounceMultiplier: 1.1,
    weightMultiplier: 0.95,
  },
];
