import { WeaponDef, WeaponId, SpecialAbilityDef, SpecialAbilityId } from '../types';

export const WEAPONS_DATABASE: Record<WeaponId, WeaponDef> = {
  ASSAULT_RIFLE: {
    id: 'ASSAULT_RIFLE',
    name: 'MK-18 SPECTER',
    category: 'Assault Rifle',
    description: 'Standard issue Nightfall tactical rifle. Reliable, high accuracy, balanced fire rate.',
    damage: 32,
    fireRate: 8.5,
    range: 120,
    magSize: 30,
    reloadTime: 1.4,
    recoil: 0.15,
    bulletSpeed: 140,
    bulletColor: '#38bdf8',
    bulletRadius: 0.22,
    cost: 0,
    unlockedByDefault: true,
    icon: 'Crosshair',
  },
  TACTICAL_SMG: {
    id: 'TACTICAL_SMG',
    name: 'VECTOR-9 SHADOW',
    category: 'Submachine Gun',
    description: 'Blistering fire rate for high close-quarters combat damage. Rapid reload.',
    damage: 22,
    fireRate: 15.0,
    range: 75,
    magSize: 45,
    reloadTime: 1.0,
    recoil: 0.25,
    bulletSpeed: 160,
    bulletColor: '#22d3ee',
    bulletRadius: 0.18,
    cost: 850,
    unlockedByDefault: false,
    icon: 'Zap',
  },
  HEAVY_SHOTGUN: {
    id: 'HEAVY_SHOTGUN',
    name: 'PULSE-12 BREACHER',
    category: 'Combat Shotgun',
    description: 'Fires heavy spread of tungsten buckshot. Devastating kinetic force up close.',
    damage: 18,
    bulletsPerShot: 7,
    spread: 0.14,
    fireRate: 2.2,
    range: 45,
    magSize: 8,
    reloadTime: 1.8,
    recoil: 0.65,
    bulletSpeed: 110,
    bulletColor: '#fb923c',
    bulletRadius: 0.25,
    cost: 1600,
    unlockedByDefault: false,
    icon: 'Flame',
  },
  SNIPER_RIFLE: {
    id: 'SNIPER_RIFLE',
    name: 'VIPER-50 AP',
    category: 'Precision Rifle',
    description: 'Anti-materiel rifle with armor piercing thermal rounds. Massive headshot damage.',
    damage: 180,
    fireRate: 1.2,
    range: 220,
    magSize: 5,
    reloadTime: 2.2,
    recoil: 0.9,
    bulletSpeed: 240,
    bulletColor: '#f43f5e',
    bulletRadius: 0.35,
    cost: 3200,
    unlockedByDefault: false,
    icon: 'Eye',
  },
  PLASMA_CANNON: {
    id: 'PLASMA_CANNON',
    name: 'NOVA CORE EX',
    category: 'Energy Weapon',
    description: 'Experimental superheated plasma accelerator. High armor penetration & splash damage.',
    damage: 85,
    isExplosive: true,
    fireRate: 3.5,
    range: 110,
    magSize: 18,
    reloadTime: 1.6,
    recoil: 0.3,
    bulletSpeed: 100,
    bulletColor: '#a855f7',
    bulletRadius: 0.45,
    cost: 5500,
    unlockedByDefault: false,
    icon: 'Radio',
  },
  ROCKET_LAUNCHER: {
    id: 'ROCKET_LAUNCHER',
    name: 'JAVELIN-X HEAVY',
    category: 'Heavy Ordnance',
    description: 'Fires high-velocity explosive missiles. Obliterates armored vehicles and boss weakpoints.',
    damage: 280,
    isExplosive: true,
    fireRate: 1.0,
    range: 140,
    magSize: 4,
    reloadTime: 2.8,
    recoil: 1.1,
    bulletSpeed: 75,
    bulletColor: '#ef4444',
    bulletRadius: 0.6,
    cost: 8000,
    unlockedByDefault: false,
    icon: 'Bomb',
  },
  MINIGUN: {
    id: 'MINIGUN',
    name: 'GATLING TITAN-6',
    category: 'Heavy Machine Gun',
    description: 'Rotary multi-barrel devastator. Unmatched sustained fire suppression.',
    damage: 28,
    fireRate: 20.0,
    range: 95,
    magSize: 120,
    reloadTime: 3.2,
    recoil: 0.4,
    bulletSpeed: 150,
    bulletColor: '#f59e0b',
    bulletRadius: 0.22,
    cost: 12000,
    unlockedByDefault: false,
    icon: 'ShieldAlert',
  },
};

export const SPECIAL_ABILITIES: Record<SpecialAbilityId, SpecialAbilityDef> = {
  ORBITAL_STRIKE: {
    id: 'ORBITAL_STRIKE',
    name: 'SATELLITE BEAM',
    description: 'Calls in precision kinetic kinetic strikes from Nightfall orbital network.',
    duration: 4.0,
    cooldown: 25.0,
    icon: 'CloudLightning',
  },
  BULLET_TIME: {
    id: 'BULLET_TIME',
    name: 'CHRONO FOCUS',
    description: 'Dilates time to 30% speed for 5 seconds while keeping player movement nimble.',
    duration: 5.0,
    cooldown: 20.0,
    icon: 'Clock',
  },
  DRONE_SWARM: {
    id: 'DRONE_SWARM',
    name: 'HUNTER DRONES',
    description: 'Launches twin autonomous micro-drones that fire automated homing lasers.',
    duration: 8.0,
    cooldown: 28.0,
    icon: 'Bot',
  },
  EMP_BLAST: {
    id: 'EMP_BLAST',
    name: 'EMP SHOCKWAVE',
    description: 'Detonates an electromagnetic pulse, disabling enemy shields and destroying incoming missiles.',
    duration: 1.5,
    cooldown: 18.0,
    icon: 'ZapOff',
  },
  OVERCHARGE_SHIELD: {
    id: 'OVERCHARGE_SHIELD',
    name: 'AEGIS BARRIER',
    description: 'Generates an invulnerable kinetic energy barrier absorbing 100% of incoming damage.',
    duration: 6.0,
    cooldown: 30.0,
    icon: 'ShieldCheck',
  },
};
